apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.secretName" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- else }}
  {{ $key }}: {{ "" | b64enc | quote }}
  {{- end }}
  {{- end }}
